export interface PlayerSeed {
  team_code: string
  name: string
  shirt_number: number
  position: 'GK' | 'DEF' | 'MID' | 'DEL'
}

export const SEED_PLAYERS: PlayerSeed[] = [
  // ─── GRUPO A ───────────────────────────────────────────────────────────────
  // MEX - México
  { team_code:'MEX', name:'Guillermo Ochoa',       shirt_number:1,  position:'GK'  },
  { team_code:'MEX', name:'Jesús Corona (Tecatito)',shirt_number:2,  position:'DEF' },
  { team_code:'MEX', name:'Jesús Gallardo',        shirt_number:3,  position:'DEF' },
  { team_code:'MEX', name:'Édson Álvarez',         shirt_number:4,  position:'MID' },
  { team_code:'MEX', name:'Johan Vásquez',         shirt_number:5,  position:'DEF' },
  { team_code:'MEX', name:'Jorge Sánchez',         shirt_number:6,  position:'DEF' },
  { team_code:'MEX', name:'Hirving Lozano',        shirt_number:7,  position:'DEL' },
  { team_code:'MEX', name:'Héctor Herrera',        shirt_number:8,  position:'MID' },
  { team_code:'MEX', name:'Raúl Jiménez',          shirt_number:9,  position:'DEL' },
  { team_code:'MEX', name:'Luis Chávez',           shirt_number:10, position:'MID' },
  { team_code:'MEX', name:'Rogelio Funes Mori',    shirt_number:11, position:'DEL' },
  { team_code:'MEX', name:'Santiago Giménez',      shirt_number:12, position:'DEL' },
  { team_code:'MEX', name:'Henry Martín',          shirt_number:13, position:'DEL' },
  { team_code:'MEX', name:'Roberto Alvarado',      shirt_number:14, position:'MID' },
  { team_code:'MEX', name:'Héctor Moreno',         shirt_number:15, position:'DEF' },
  { team_code:'MEX', name:'Orbelín Pineda',        shirt_number:16, position:'MID' },
  { team_code:'MEX', name:'César Montes',          shirt_number:17, position:'DEF' },

  // RSA - Sudáfrica
  { team_code:'RSA', name:'Ronwen Williams',       shirt_number:1,  position:'GK'  },
  { team_code:'RSA', name:'Teboho Mokoena',        shirt_number:5,  position:'MID' },
  { team_code:'RSA', name:'Rushine De Reuck',      shirt_number:4,  position:'DEF' },
  { team_code:'RSA', name:'Siyanda Xulu',          shirt_number:6,  position:'DEF' },
  { team_code:'RSA', name:'Bongani Zungu',         shirt_number:8,  position:'MID' },
  { team_code:'RSA', name:'Themba Zwane',          shirt_number:10, position:'MID' },
  { team_code:'RSA', name:'Percy Tau',             shirt_number:11, position:'DEL' },
  { team_code:'RSA', name:'Lyle Foster',           shirt_number:9,  position:'DEL' },
  { team_code:'RSA', name:'Evidence Makgopa',      shirt_number:14, position:'DEL' },
  { team_code:'RSA', name:'Lebo Mothiba',          shirt_number:18, position:'DEL' },
  { team_code:'RSA', name:'Keagan Dolly',          shirt_number:17, position:'DEL' },
  { team_code:'RSA', name:'Luther Singh',          shirt_number:20, position:'MID' },

  // KOR - Corea del Sur
  { team_code:'KOR', name:'Kim Seung-gyu',         shirt_number:1,  position:'GK'  },
  { team_code:'KOR', name:'Kim Min-jae',           shirt_number:3,  position:'DEF' },
  { team_code:'KOR', name:'Kim Young-gwon',        shirt_number:4,  position:'DEF' },
  { team_code:'KOR', name:'Hwang In-beom',         shirt_number:7,  position:'MID' },
  { team_code:'KOR', name:'Lee Jae-sung',          shirt_number:8,  position:'MID' },
  { team_code:'KOR', name:'Son Heung-min',         shirt_number:7,  position:'DEL' },
  { team_code:'KOR', name:'Hwang Ui-jo',           shirt_number:9,  position:'DEL' },
  { team_code:'KOR', name:'Cho Gue-sung',          shirt_number:11, position:'DEL' },
  { team_code:'KOR', name:'Lee Kang-in',           shirt_number:10, position:'MID' },
  { team_code:'KOR', name:'Oh Hyeon-gyu',          shirt_number:18, position:'DEL' },
  { team_code:'KOR', name:'Kwon Chang-hoon',       shirt_number:17, position:'MID' },
  { team_code:'KOR', name:'Kim Jin-su',            shirt_number:12, position:'DEF' },

  // CZE - República Checa
  { team_code:'CZE', name:'Jiří Pavlenka',         shirt_number:1,  position:'GK'  },
  { team_code:'CZE', name:'Vladimír Coufal',       shirt_number:2,  position:'DEF' },
  { team_code:'CZE', name:'Tomáš Souček',          shirt_number:5,  position:'MID' },
  { team_code:'CZE', name:'Patrik Schick',         shirt_number:9,  position:'DEL' },
  { team_code:'CZE', name:'Ondřej Duda',           shirt_number:10, position:'MID' },
  { team_code:'CZE', name:'Adam Hložek',           shirt_number:11, position:'DEL' },
  { team_code:'CZE', name:'Jan Kuchta',            shirt_number:14, position:'DEL' },
  { team_code:'CZE', name:'Jakub Brabec',          shirt_number:4,  position:'DEF' },
  { team_code:'CZE', name:'Michal Sadílek',        shirt_number:17, position:'MID' },
  { team_code:'CZE', name:'Tomáš Holeš',          shirt_number:6,  position:'MID' },
  { team_code:'CZE', name:'Antonín Barák',         shirt_number:20, position:'MID' },

  // ─── GRUPO B ───────────────────────────────────────────────────────────────
  // CAN - Canadá
  { team_code:'CAN', name:'Milan Borjan',          shirt_number:1,  position:'GK'  },
  { team_code:'CAN', name:'Alphonso Davies',       shirt_number:3,  position:'DEF' },
  { team_code:'CAN', name:'Kamal Miller',          shirt_number:4,  position:'DEF' },
  { team_code:'CAN', name:'Steven Vitória',        shirt_number:5,  position:'DEF' },
  { team_code:'CAN', name:'Richie Laryea',         shirt_number:2,  position:'DEF' },
  { team_code:'CAN', name:'Stephen Eustáquio',     shirt_number:7,  position:'MID' },
  { team_code:'CAN', name:'Mark-Anthony Kaye',     shirt_number:8,  position:'MID' },
  { team_code:'CAN', name:'Jonathan David',        shirt_number:9,  position:'DEL' },
  { team_code:'CAN', name:'Tajon Buchanan',        shirt_number:11, position:'DEL' },
  { team_code:'CAN', name:'Cyle Larin',            shirt_number:17, position:'DEL' },
  { team_code:'CAN', name:'Ismaël Koné',           shirt_number:16, position:'MID' },
  { team_code:'CAN', name:'Liam Millar',           shirt_number:14, position:'DEL' },
  { team_code:'CAN', name:'Junior Hoilett',        shirt_number:10, position:'MID' },
  { team_code:'CAN', name:'Ali Ahmed',             shirt_number:22, position:'MID' },

  // BIH - Bosnia y Herz.
  { team_code:'BIH', name:'Ibrahim Šehić',         shirt_number:1,  position:'GK'  },
  { team_code:'BIH', name:'Sead Kolašinac',        shirt_number:3,  position:'DEF' },
  { team_code:'BIH', name:'Anel Ahmedhodžić',      shirt_number:5,  position:'DEF' },
  { team_code:'BIH', name:'Muhamed Bešić',         shirt_number:8,  position:'MID' },
  { team_code:'BIH', name:'Edin Džeko',            shirt_number:10, position:'DEL' },
  { team_code:'BIH', name:'Ermedin Demirović',     shirt_number:9,  position:'DEL' },
  { team_code:'BIH', name:'Nedim Bajrami',         shirt_number:7,  position:'MID' },
  { team_code:'BIH', name:'Amar Dedić',            shirt_number:2,  position:'DEF' },
  { team_code:'BIH', name:'Nermin Zolotić',        shirt_number:4,  position:'DEF' },
  { team_code:'BIH', name:'Luka Menalo',           shirt_number:11, position:'DEL' },

  // QAT - Qatar
  { team_code:'QAT', name:'Meshaal Barsham',       shirt_number:1,  position:'GK'  },
  { team_code:'QAT', name:'Pedro Miguel',          shirt_number:3,  position:'DEF' },
  { team_code:'QAT', name:'Bassam Al-Rawi',        shirt_number:4,  position:'DEF' },
  { team_code:'QAT', name:'Karim Boudiaf',         shirt_number:6,  position:'MID' },
  { team_code:'QAT', name:'Akram Afif',            shirt_number:11, position:'DEL' },
  { team_code:'QAT', name:'Almoez Ali',            shirt_number:19, position:'DEL' },
  { team_code:'QAT', name:'Hassan Al-Haydos',      shirt_number:10, position:'MID' },
  { team_code:'QAT', name:'Mohammed Muntari',      shirt_number:21, position:'DEL' },
  { team_code:'QAT', name:'Abdelkarim Hassan',     shirt_number:5,  position:'DEF' },
  { team_code:'QAT', name:'Ismaeel Mohammad',      shirt_number:9,  position:'DEL' },
  { team_code:'QAT', name:'Homam Ahmed',           shirt_number:14, position:'MID' },

  // SUI - Suiza
  { team_code:'SUI', name:'Yann Sommer',           shirt_number:1,  position:'GK'  },
  { team_code:'SUI', name:'Manuel Akanji',         shirt_number:5,  position:'DEF' },
  { team_code:'SUI', name:'Nico Elvedi',           shirt_number:4,  position:'DEF' },
  { team_code:'SUI', name:'Silvan Widmer',         shirt_number:2,  position:'DEF' },
  { team_code:'SUI', name:'Granit Xhaka',          shirt_number:10, position:'MID' },
  { team_code:'SUI', name:'Remo Freuler',          shirt_number:8,  position:'MID' },
  { team_code:'SUI', name:'Denis Zakaria',         shirt_number:6,  position:'MID' },
  { team_code:'SUI', name:'Breel Embolo',          shirt_number:7,  position:'DEL' },
  { team_code:'SUI', name:'Haris Seferović',       shirt_number:9,  position:'DEL' },
  { team_code:'SUI', name:'Fabian Rieder',         shirt_number:11, position:'MID' },
  { team_code:'SUI', name:'Dan Ndoye',             shirt_number:14, position:'DEL' },
  { team_code:'SUI', name:'Zeki Amdouni',         shirt_number:16, position:'DEL' },

  // ─── GRUPO C ───────────────────────────────────────────────────────────────
  // BRA - Brasil
  { team_code:'BRA', name:'Alisson Becker',        shirt_number:1,  position:'GK'  },
  { team_code:'BRA', name:'Danilo',                shirt_number:2,  position:'DEF' },
  { team_code:'BRA', name:'Marquinhos',            shirt_number:4,  position:'DEF' },
  { team_code:'BRA', name:'Éder Militão',          shirt_number:3,  position:'DEF' },
  { team_code:'BRA', name:'Gabriel Magalhães',     shirt_number:6,  position:'DEF' },
  { team_code:'BRA', name:'Guilherme Arana',       shirt_number:6,  position:'DEF' },
  { team_code:'BRA', name:'Casemiro',              shirt_number:5,  position:'MID' },
  { team_code:'BRA', name:'Lucas Paquetá',         shirt_number:10, position:'MID' },
  { team_code:'BRA', name:'Bruno Guimarães',       shirt_number:8,  position:'MID' },
  { team_code:'BRA', name:'Raphinha',              shirt_number:11, position:'DEL' },
  { team_code:'BRA', name:'Vinícius Jr.',          shirt_number:7,  position:'DEL' },
  { team_code:'BRA', name:'Rodrygo',               shirt_number:9,  position:'DEL' },
  { team_code:'BRA', name:'Gabriel Jesus',         shirt_number:9,  position:'DEL' },
  { team_code:'BRA', name:'Richarlison',           shirt_number:9,  position:'DEL' },
  { team_code:'BRA', name:'Endrick',               shirt_number:19, position:'DEL' },
  { team_code:'BRA', name:'Neymar Jr.',            shirt_number:10, position:'DEL' },

  // MAR - Marruecos
  { team_code:'MAR', name:'Yassine Bounou (Bono)', shirt_number:1,  position:'GK'  },
  { team_code:'MAR', name:'Achraf Hakimi',         shirt_number:2,  position:'DEF' },
  { team_code:'MAR', name:'Nayef Aguerd',          shirt_number:5,  position:'DEF' },
  { team_code:'MAR', name:'Romain Saïss',          shirt_number:6,  position:'DEF' },
  { team_code:'MAR', name:'Noussair Mazraoui',     shirt_number:3,  position:'DEF' },
  { team_code:'MAR', name:'Sofyan Amrabat',        shirt_number:4,  position:'MID' },
  { team_code:'MAR', name:'Azzedine Ounahi',       shirt_number:8,  position:'MID' },
  { team_code:'MAR', name:'Hakim Ziyech',          shirt_number:7,  position:'MID' },
  { team_code:'MAR', name:'Youssef En-Nesyri',     shirt_number:9,  position:'DEL' },
  { team_code:'MAR', name:'Sofiane Boufal',        shirt_number:11, position:'DEL' },
  { team_code:'MAR', name:'Abde Ezzalzouli',       shirt_number:17, position:'DEL' },
  { team_code:'MAR', name:'Brahim Díaz',           shirt_number:10, position:'MID' },
  { team_code:'MAR', name:'Ryan Mmaee',            shirt_number:19, position:'DEL' },

  // HAI - Haití
  { team_code:'HAI', name:'Duckens Nazon',         shirt_number:7,  position:'DEL' },
  { team_code:'HAI', name:'Frantzdy Pierrot',      shirt_number:9,  position:'DEL' },
  { team_code:'HAI', name:'Olivier Verdon',        shirt_number:4,  position:'DEF' },
  { team_code:'HAI', name:'Derrick Etienne Jr.',   shirt_number:11, position:'DEL' },
  { team_code:'HAI', name:'Peterson Joseph',       shirt_number:5,  position:'MID' },
  { team_code:'HAI', name:'Wilde-Donald Guerrier', shirt_number:10, position:'MID' },
  { team_code:'HAI', name:'James Léandre',         shirt_number:8,  position:'MID' },
  { team_code:'HAI', name:'Mechack Jérôme',        shirt_number:3,  position:'DEF' },
  { team_code:'HAI', name:'Romelson Viard',        shirt_number:1,  position:'GK'  },

  // SCO - Escocia
  { team_code:'SCO', name:'Angus Gunn',            shirt_number:1,  position:'GK'  },
  { team_code:'SCO', name:'Andy Robertson',        shirt_number:3,  position:'DEF' },
  { team_code:'SCO', name:'Kieran Tierney',        shirt_number:5,  position:'DEF' },
  { team_code:'SCO', name:'Scott McTominay',       shirt_number:8,  position:'MID' },
  { team_code:'SCO', name:'John McGinn',           shirt_number:7,  position:'MID' },
  { team_code:'SCO', name:'Callum McGregor',       shirt_number:6,  position:'MID' },
  { team_code:'SCO', name:'Stuart Armstrong',      shirt_number:10, position:'MID' },
  { team_code:'SCO', name:'Lyndon Dykes',          shirt_number:9,  position:'DEL' },
  { team_code:'SCO', name:'Lawrence Shankland',    shirt_number:14, position:'DEL' },
  { team_code:'SCO', name:'Che Adams',             shirt_number:11, position:'DEL' },
  { team_code:'SCO', name:'Ryan Christie',        shirt_number:12, position:'MID' },
  { team_code:'SCO', name:'Jack Hendry',           shirt_number:4,  position:'DEF' },

  // ─── GRUPO D ───────────────────────────────────────────────────────────────
  // USA - Estados Unidos
  { team_code:'USA', name:'Matt Turner',           shirt_number:1,  position:'GK'  },
  { team_code:'USA', name:'Sergino Dest',          shirt_number:2,  position:'DEF' },
  { team_code:'USA', name:'Tim Ream',              shirt_number:5,  position:'DEF' },
  { team_code:'USA', name:'Walker Zimmermann',     shirt_number:4,  position:'DEF' },
  { team_code:'USA', name:'Antonee Robinson',      shirt_number:3,  position:'DEF' },
  { team_code:'USA', name:'Tyler Adams',           shirt_number:4,  position:'MID' },
  { team_code:'USA', name:'Weston McKennie',       shirt_number:8,  position:'MID' },
  { team_code:'USA', name:'Yunus Musah',           shirt_number:6,  position:'MID' },
  { team_code:'USA', name:'Christian Pulisic',     shirt_number:10, position:'MID' },
  { team_code:'USA', name:'Giovanni Reyna',        shirt_number:7,  position:'MID' },
  { team_code:'USA', name:'Ricardo Pepi',          shirt_number:9,  position:'DEL' },
  { team_code:'USA', name:'Folarin Balogun',       shirt_number:19, position:'DEL' },
  { team_code:'USA', name:'Tim Weah',              shirt_number:11, position:'DEL' },
  { team_code:'USA', name:'Malik Tillman',         shirt_number:14, position:'MID' },

  // PAR - Paraguay
  { team_code:'PAR', name:'Antony Silva',          shirt_number:1,  position:'GK'  },
  { team_code:'PAR', name:'Fabián Balbuena',       shirt_number:5,  position:'DEF' },
  { team_code:'PAR', name:'Gustavo Gómez',         shirt_number:4,  position:'DEF' },
  { team_code:'PAR', name:'Omar Alderete',         shirt_number:3,  position:'DEF' },
  { team_code:'PAR', name:'Ángel Cardozo',         shirt_number:2,  position:'DEF' },
  { team_code:'PAR', name:'Andrés Cubas',          shirt_number:6,  position:'MID' },
  { team_code:'PAR', name:'Richard Sánchez',       shirt_number:8,  position:'MID' },
  { team_code:'PAR', name:'Miguel Almirón',        shirt_number:10, position:'MID' },
  { team_code:'PAR', name:'Julio Enciso',          shirt_number:11, position:'DEL' },
  { team_code:'PAR', name:'Carlos González',       shirt_number:9,  position:'DEL' },
  { team_code:'PAR', name:'Antonio Sanabria',      shirt_number:7,  position:'DEL' },
  { team_code:'PAR', name:'Braian Ojeda',          shirt_number:16, position:'MID' },
  { team_code:'PAR', name:'Sergio Almirón',        shirt_number:17, position:'DEL' },

  // AUS - Australia
  { team_code:'AUS', name:'Mathew Ryan',           shirt_number:1,  position:'GK'  },
  { team_code:'AUS', name:'Milos Degenek',         shirt_number:2,  position:'DEF' },
  { team_code:'AUS', name:'Harry Souttar',         shirt_number:4,  position:'DEF' },
  { team_code:'AUS', name:'Aziz Behich',           shirt_number:3,  position:'DEF' },
  { team_code:'AUS', name:'Riley McGree',          shirt_number:8,  position:'MID' },
  { team_code:'AUS', name:'Mathew Leckie',         shirt_number:7,  position:'DEL' },
  { team_code:'AUS', name:'Martin Boyle',          shirt_number:11, position:'DEL' },
  { team_code:'AUS', name:'Ajdin Hrustic',         shirt_number:10, position:'MID' },
  { team_code:'AUS', name:'Mitchell Duke',         shirt_number:9,  position:'DEL' },
  { team_code:'AUS', name:'Garang Kuol',           shirt_number:19, position:'DEL' },
  { team_code:'AUS', name:'Awer Mabil',            shirt_number:17, position:'DEL' },
  { team_code:'AUS', name:'Cameron Devlin',        shirt_number:6,  position:'MID' },

  // TUR - Turquía
  { team_code:'TUR', name:'Uğurcan Çakır',         shirt_number:1,  position:'GK'  },
  { team_code:'TUR', name:'Zeki Çelik',            shirt_number:2,  position:'DEF' },
  { team_code:'TUR', name:'Merih Demiral',         shirt_number:3,  position:'DEF' },
  { team_code:'TUR', name:'Kaan Ayhan',            shirt_number:5,  position:'DEF' },
  { team_code:'TUR', name:'Ferdi Kadıoğlu',        shirt_number:6,  position:'DEF' },
  { team_code:'TUR', name:'Hakan Çalhanoğlu',      shirt_number:8,  position:'MID' },
  { team_code:'TUR', name:'Orkun Kökçü',           shirt_number:7,  position:'MID' },
  { team_code:'TUR', name:'Arda Güler',            shirt_number:10, position:'MID' },
  { team_code:'TUR', name:'Kenan Yıldız',          shirt_number:11, position:'DEL' },
  { team_code:'TUR', name:'Barış Alper Yılmaz',    shirt_number:14, position:'DEL' },
  { team_code:'TUR', name:'Yusuf Yazıcı',          shirt_number:15, position:'MID' },
  { team_code:'TUR', name:'Halil Dervişoğlu',      shirt_number:9,  position:'DEL' },
  { team_code:'TUR', name:'Çağlar Söyüncü',        shirt_number:4,  position:'DEF' },

  // ─── GRUPO E ───────────────────────────────────────────────────────────────
  // GER - Alemania
  { team_code:'GER', name:'Manuel Neuer',          shirt_number:1,  position:'GK'  },
  { team_code:'GER', name:'Antonio Rüdiger',       shirt_number:2,  position:'DEF' },
  { team_code:'GER', name:'Joshua Kimmich',        shirt_number:6,  position:'MID' },
  { team_code:'GER', name:'Ilkay Gündogan',        shirt_number:21, position:'MID' },
  { team_code:'GER', name:'Leon Goretzka',         shirt_number:8,  position:'MID' },
  { team_code:'GER', name:'Robert Andrich',        shirt_number:23, position:'MID' },
  { team_code:'GER', name:'Leroy Sané',            shirt_number:10, position:'DEL' },
  { team_code:'GER', name:'Jamal Musiala',         shirt_number:14, position:'MID' },
  { team_code:'GER', name:'Kai Havertz',           shirt_number:7,  position:'DEL' },
  { team_code:'GER', name:'Florian Wirtz',         shirt_number:11, position:'MID' },
  { team_code:'GER', name:'Niclas Füllkrug',       shirt_number:9,  position:'DEL' },
  { team_code:'GER', name:'Serge Gnabry',          shirt_number:17, position:'DEL' },
  { team_code:'GER', name:'Thomas Müller',         shirt_number:25, position:'DEL' },
  { team_code:'GER', name:'Marc-André ter Stegen', shirt_number:22, position:'GK'  },
  { team_code:'GER', name:'Maximilian Mittelstädt',shirt_number:5,  position:'DEF' },

  // CUW - Curazao
  { team_code:'CUW', name:'Eloy Room',             shirt_number:1,  position:'GK'  },
  { team_code:'CUW', name:'Cuco Martina',          shirt_number:3,  position:'DEF' },
  { team_code:'CUW', name:'Leandro Bacuna',        shirt_number:8,  position:'MID' },
  { team_code:'CUW', name:'Ruwayne Bacuna',        shirt_number:16, position:'DEF' },
  { team_code:'CUW', name:'Rangelo Janga',         shirt_number:9,  position:'DEL' },
  { team_code:'CUW', name:'Quentin Overman',       shirt_number:7,  position:'MID' },
  { team_code:'CUW', name:'Corydon Ruiter',        shirt_number:11, position:'DEL' },
  { team_code:'CUW', name:'Roshon van der Berg',   shirt_number:14, position:'DEF' },
  { team_code:'CUW', name:'Rubio Rubin',           shirt_number:10, position:'DEL' },

  // CIV - Costa de Marfil
  { team_code:'CIV', name:'Yahia Fofana',          shirt_number:1,  position:'GK'  },
  { team_code:'CIV', name:'Serge Aurier',          shirt_number:2,  position:'DEF' },
  { team_code:'CIV', name:'Simon Deli',            shirt_number:5,  position:'DEF' },
  { team_code:'CIV', name:'Wilfried Zaha',         shirt_number:7,  position:'DEL' },
  { team_code:'CIV', name:'Nicolas Pépé',          shirt_number:11, position:'DEL' },
  { team_code:'CIV', name:'Sébastien Haller',      shirt_number:9,  position:'DEL' },
  { team_code:'CIV', name:'Frank Kessié',          shirt_number:8,  position:'MID' },
  { team_code:'CIV', name:'Ibrahim Sangaré',       shirt_number:6,  position:'MID' },
  { team_code:'CIV', name:'Maxwell Cornet',        shirt_number:14, position:'DEL' },
  { team_code:'CIV', name:'Oumar Diakité',         shirt_number:10, position:'MID' },
  { team_code:'CIV', name:'Jean-Philippe Krasso',  shirt_number:17, position:'DEL' },
  { team_code:'CIV', name:'Karim Konaté',          shirt_number:19, position:'DEL' },

  // ECU - Ecuador
  { team_code:'ECU', name:'Alexander Domínguez',   shirt_number:1,  position:'GK'  },
  { team_code:'ECU', name:'Piero Hincapié',        shirt_number:3,  position:'DEF' },
  { team_code:'ECU', name:'William Pacho',         shirt_number:4,  position:'DEF' },
  { team_code:'ECU', name:'Ángelo Preciado',       shirt_number:2,  position:'DEF' },
  { team_code:'ECU', name:'Byron Castillo',        shirt_number:16, position:'DEF' },
  { team_code:'ECU', name:'Moisés Caicedo',        shirt_number:10, position:'MID' },
  { team_code:'ECU', name:'Kendry Páez',           shirt_number:8,  position:'MID' },
  { team_code:'ECU', name:'Jeremy Sarmiento',      shirt_number:7,  position:'MID' },
  { team_code:'ECU', name:'Gonzalo Plata',         shirt_number:11, position:'DEL' },
  { team_code:'ECU', name:'Djorkaeff Reasco',      shirt_number:17, position:'DEL' },
  { team_code:'ECU', name:'Kevin Rodríguez',       shirt_number:9,  position:'DEL' },
  { team_code:'ECU', name:'Enner Valencia',        shirt_number:13, position:'DEL' },

  // ─── GRUPO F ───────────────────────────────────────────────────────────────
  // NED - Países Bajos
  { team_code:'NED', name:'Jasper Cillessen',      shirt_number:1,  position:'GK'  },
  { team_code:'NED', name:'Virgil van Dijk',       shirt_number:4,  position:'DEF' },
  { team_code:'NED', name:'Matthijs de Ligt',      shirt_number:3,  position:'DEF' },
  { team_code:'NED', name:'Nathan Aké',            shirt_number:5,  position:'DEF' },
  { team_code:'NED', name:'Denzel Dumfries',       shirt_number:2,  position:'DEF' },
  { team_code:'NED', name:'Frenkie de Jong',       shirt_number:21, position:'MID' },
  { team_code:'NED', name:'Tijjani Reijnders',     shirt_number:8,  position:'MID' },
  { team_code:'NED', name:'Ryan Gravenberch',      shirt_number:6,  position:'MID' },
  { team_code:'NED', name:'Xavi Simons',           shirt_number:10, position:'MID' },
  { team_code:'NED', name:'Cody Gakpo',            shirt_number:11, position:'DEL' },
  { team_code:'NED', name:'Donyell Malen',         shirt_number:9,  position:'DEL' },
  { team_code:'NED', name:'Wout Weghorst',         shirt_number:19, position:'DEL' },
  { team_code:'NED', name:'Steven Bergwijn',       shirt_number:7,  position:'DEL' },
  { team_code:'NED', name:'Memphis Depay',         shirt_number:10, position:'DEL' },

  // JPN - Japón
  { team_code:'JPN', name:'Shuichi Gonda',         shirt_number:1,  position:'GK'  },
  { team_code:'JPN', name:'Maya Yoshida',          shirt_number:4,  position:'DEF' },
  { team_code:'JPN', name:'Ko Itakura',            shirt_number:5,  position:'DEF' },
  { team_code:'JPN', name:'Takehiro Tomiyasu',     shirt_number:3,  position:'DEF' },
  { team_code:'JPN', name:'Wataru Endo',           shirt_number:7,  position:'MID' },
  { team_code:'JPN', name:'Hidemasa Morita',       shirt_number:8,  position:'MID' },
  { team_code:'JPN', name:'Takumi Minamino',       shirt_number:9,  position:'DEL' },
  { team_code:'JPN', name:'Daichi Kamada',         shirt_number:10, position:'MID' },
  { team_code:'JPN', name:'Ritsu Doan',            shirt_number:11, position:'MID' },
  { team_code:'JPN', name:'Kaoru Mitoma',          shirt_number:14, position:'DEL' },
  { team_code:'JPN', name:'Junya Ito',             shirt_number:17, position:'DEL' },
  { team_code:'JPN', name:'Ayase Ueda',            shirt_number:15, position:'DEL' },
  { team_code:'JPN', name:'Takefusa Kubo',         shirt_number:21, position:'MID' },
  { team_code:'JPN', name:'Kyogo Furuhashi',       shirt_number:20, position:'DEL' },

  // SWE - Suecia
  { team_code:'SWE', name:'Robin Olsen',           shirt_number:1,  position:'GK'  },
  { team_code:'SWE', name:'Victor Nilsson Lindelöf',shirt_number:2, position:'DEF' },
  { team_code:'SWE', name:'Isak Hien',             shirt_number:5,  position:'DEF' },
  { team_code:'SWE', name:'Ludwig Augustinsson',   shirt_number:3,  position:'DEF' },
  { team_code:'SWE', name:'Emil Forsberg',         shirt_number:10, position:'MID' },
  { team_code:'SWE', name:'Mattias Svanberg',      shirt_number:8,  position:'MID' },
  { team_code:'SWE', name:'Dejan Kulusevski',      shirt_number:7,  position:'MID' },
  { team_code:'SWE', name:'Alexander Isak',        shirt_number:11, position:'DEL' },
  { team_code:'SWE', name:'Viktor Gyökeres',       shirt_number:9,  position:'DEL' },
  { team_code:'SWE', name:'Anthony Elanga',        shirt_number:17, position:'DEL' },
  { team_code:'SWE', name:'Jesper Karlsson',       shirt_number:14, position:'DEL' },
  { team_code:'SWE', name:'Marcus Danielson',      shirt_number:4,  position:'DEF' },

  // TUN - Túnez
  { team_code:'TUN', name:'Aymen Dahmen',          shirt_number:1,  position:'GK'  },
  { team_code:'TUN', name:'Dylan Bronn',           shirt_number:5,  position:'DEF' },
  { team_code:'TUN', name:'Montassar Talbi',       shirt_number:4,  position:'DEF' },
  { team_code:'TUN', name:'Ali Maaloul',           shirt_number:3,  position:'DEF' },
  { team_code:'TUN', name:'Ellyes Skhiri',         shirt_number:6,  position:'MID' },
  { team_code:'TUN', name:'Hannibal Mejbri',       shirt_number:8,  position:'MID' },
  { team_code:'TUN', name:'Wahbi Khazri',          shirt_number:10, position:'MID' },
  { team_code:'TUN', name:'Seifeddine Jaziri',     shirt_number:9,  position:'DEL' },
  { team_code:'TUN', name:'Youssef Msakni',        shirt_number:7,  position:'DEL' },
  { team_code:'TUN', name:'Anis Ben Slimane',      shirt_number:11, position:'MID' },
  { team_code:'TUN', name:'Naim Sliti',            shirt_number:14, position:'DEL' },

  // ─── GRUPO G ───────────────────────────────────────────────────────────────
  // BEL - Bélgica
  { team_code:'BEL', name:'Thibaut Courtois',      shirt_number:1,  position:'GK'  },
  { team_code:'BEL', name:'Thomas Meunier',        shirt_number:2,  position:'DEF' },
  { team_code:'BEL', name:'Wout Faes',             shirt_number:4,  position:'DEF' },
  { team_code:'BEL', name:'Arthur Theate',         shirt_number:5,  position:'DEF' },
  { team_code:'BEL', name:'Kevin De Bruyne',       shirt_number:7,  position:'MID' },
  { team_code:'BEL', name:'Romelu Lukaku',         shirt_number:9,  position:'DEL' },
  { team_code:'BEL', name:'Yannick Carrasco',      shirt_number:11, position:'DEL' },
  { team_code:'BEL', name:'Charles De Ketelaere',  shirt_number:14, position:'MID' },
  { team_code:'BEL', name:'Leandro Trossard',      shirt_number:19, position:'DEL' },
  { team_code:'BEL', name:'Alexis Saelemaekers',   shirt_number:15, position:'MID' },
  { team_code:'BEL', name:'Loïs Openda',           shirt_number:20, position:'DEL' },
  { team_code:'BEL', name:'Amadou Onana',          shirt_number:8,  position:'MID' },
  { team_code:'BEL', name:'Johan Bakayoko',        shirt_number:17, position:'DEL' },
  { team_code:'BEL', name:'Zeno Debast',           shirt_number:3,  position:'DEF' },

  // EGY - Egipto
  { team_code:'EGY', name:'Mohamed El-Shenawy',    shirt_number:1,  position:'GK'  },
  { team_code:'EGY', name:'Ahmed Hegazy',          shirt_number:5,  position:'DEF' },
  { team_code:'EGY', name:'Omar Gaber',            shirt_number:3,  position:'DEF' },
  { team_code:'EGY', name:'Mohamed Elneny',        shirt_number:4,  position:'MID' },
  { team_code:'EGY', name:'Tarek Hamed',           shirt_number:6,  position:'MID' },
  { team_code:'EGY', name:'Mohamed Salah',         shirt_number:10, position:'DEL' },
  { team_code:'EGY', name:'Trezeguet',             shirt_number:7,  position:'DEL' },
  { team_code:'EGY', name:'Mostafa Mohamed',       shirt_number:9,  position:'DEL' },
  { team_code:'EGY', name:'Ramadan Sobhi',         shirt_number:11, position:'MID' },
  { team_code:'EGY', name:'Marwan Hamdi',          shirt_number:14, position:'DEL' },
  { team_code:'EGY', name:'Hussein El-Shahat',     shirt_number:8,  position:'MID' },
  { team_code:'EGY', name:'Hamdi Fathi',           shirt_number:17, position:'MID' },

  // IRN - Irán
  { team_code:'IRN', name:'Alireza Beiranvand',    shirt_number:1,  position:'GK'  },
  { team_code:'IRN', name:'Roozbeh Cheshmi',       shirt_number:5,  position:'DEF' },
  { team_code:'IRN', name:'Morteza Pouraliganji',  shirt_number:4,  position:'DEF' },
  { team_code:'IRN', name:'Ehsan Hajsafi',         shirt_number:3,  position:'DEF' },
  { team_code:'IRN', name:'Saeid Ezatolahi',       shirt_number:6,  position:'MID' },
  { team_code:'IRN', name:'Ahmad Nourollahi',      shirt_number:8,  position:'MID' },
  { team_code:'IRN', name:'Mehdi Taremi',          shirt_number:9,  position:'DEL' },
  { team_code:'IRN', name:'Sardar Azmoun',         shirt_number:11, position:'DEL' },
  { team_code:'IRN', name:'Alireza Jahanbakhsh',   shirt_number:7,  position:'DEL' },
  { team_code:'IRN', name:'Saman Ghoddos',         shirt_number:14, position:'MID' },
  { team_code:'IRN', name:'Ali Gholizadeh',        shirt_number:17, position:'DEL' },
  { team_code:'IRN', name:'Mehdi Torabi',          shirt_number:10, position:'MID' },

  // NZL - Nueva Zelanda
  { team_code:'NZL', name:'Michael Woud',          shirt_number:1,  position:'GK'  },
  { team_code:'NZL', name:'Tommy Smith',           shirt_number:2,  position:'DEF' },
  { team_code:'NZL', name:'Liberato Cacace',       shirt_number:3,  position:'DEF' },
  { team_code:'NZL', name:'Joe Bell',              shirt_number:8,  position:'MID' },
  { team_code:'NZL', name:'Marco Rojas',           shirt_number:7,  position:'DEL' },
  { team_code:'NZL', name:'Chris Wood',            shirt_number:9,  position:'DEL' },
  { team_code:'NZL', name:'Callan Elliot',         shirt_number:14, position:'DEL' },
  { team_code:'NZL', name:'Matthew Garbett',       shirt_number:10, position:'MID' },
  { team_code:'NZL', name:'Ben Old',               shirt_number:11, position:'DEL' },
  { team_code:'NZL', name:'Clayton Lewis',         shirt_number:6,  position:'MID' },
  { team_code:'NZL', name:'Tim Payne',             shirt_number:5,  position:'DEF' },

  // ─── GRUPO H ───────────────────────────────────────────────────────────────
  // ESP - España
  { team_code:'ESP', name:'David Raya',            shirt_number:1,  position:'GK'  },
  { team_code:'ESP', name:'Unai Simón',            shirt_number:23, position:'GK'  },
  { team_code:'ESP', name:'Dani Carvajal',         shirt_number:2,  position:'DEF' },
  { team_code:'ESP', name:'Pau Cubarsí',           shirt_number:4,  position:'DEF' },
  { team_code:'ESP', name:'Robin Le Normand',      shirt_number:3,  position:'DEF' },
  { team_code:'ESP', name:'Alejandro Grimaldo',    shirt_number:3,  position:'DEF' },
  { team_code:'ESP', name:'Rodri',                 shirt_number:16, position:'MID' },
  { team_code:'ESP', name:'Pedri',                 shirt_number:26, position:'MID' },
  { team_code:'ESP', name:'Gavi',                  shirt_number:14, position:'MID' },
  { team_code:'ESP', name:'Fabián Ruiz',           shirt_number:8,  position:'MID' },
  { team_code:'ESP', name:'Lamine Yamal',          shirt_number:19, position:'DEL' },
  { team_code:'ESP', name:'Nico Williams',         shirt_number:11, position:'DEL' },
  { team_code:'ESP', name:'Dani Olmo',             shirt_number:10, position:'MID' },
  { team_code:'ESP', name:'Álvaro Morata',         shirt_number:7,  position:'DEL' },
  { team_code:'ESP', name:'Mikel Oyarzabal',       shirt_number:22, position:'DEL' },
  { team_code:'ESP', name:'Ferran Torres',         shirt_number:19, position:'DEL' },
  { team_code:'ESP', name:'Yeremy Pino',           shirt_number:21, position:'DEL' },

  // CPV - Cabo Verde
  { team_code:'CPV', name:'Vozinha',               shirt_number:1,  position:'GK'  },
  { team_code:'CPV', name:'Roberto Lopes',         shirt_number:5,  position:'DEF' },
  { team_code:'CPV', name:'Kenny Rocha',           shirt_number:8,  position:'MID' },
  { team_code:'CPV', name:'Patrick Andrade',       shirt_number:6,  position:'MID' },
  { team_code:'CPV', name:'Garry Rodrigues',       shirt_number:7,  position:'DEL' },
  { team_code:'CPV', name:'Júlio Tavares',         shirt_number:9,  position:'DEL' },
  { team_code:'CPV', name:'Ryan Mendes',           shirt_number:11, position:'DEL' },
  { team_code:'CPV', name:'Jovane Cabral',         shirt_number:10, position:'DEL' },
  { team_code:'CPV', name:'Marco Soares',          shirt_number:4,  position:'DEF' },
  { team_code:'CPV', name:'Bryan Tavares',         shirt_number:14, position:'MID' },

  // KSA - Arabia Saudita
  { team_code:'KSA', name:'Mohammed Al-Owais',     shirt_number:1,  position:'GK'  },
  { team_code:'KSA', name:'Yasser Al-Shahrani',    shirt_number:3,  position:'DEF' },
  { team_code:'KSA', name:'Ali Al-Bulaihi',        shirt_number:5,  position:'DEF' },
  { team_code:'KSA', name:'Abdulelah Al-Amri',     shirt_number:4,  position:'DEF' },
  { team_code:'KSA', name:'Salman Al-Faraj',       shirt_number:6,  position:'MID' },
  { team_code:'KSA', name:'Firas Al-Buraikan',     shirt_number:9,  position:'DEL' },
  { team_code:'KSA', name:'Salem Al-Dawsari',      shirt_number:10, position:'DEL' },
  { team_code:'KSA', name:'Abdullah Al-Hamdan',    shirt_number:11, position:'DEL' },
  { team_code:'KSA', name:'Hattan Bahebri',        shirt_number:7,  position:'MID' },
  { team_code:'KSA', name:'Sami Al-Najei',         shirt_number:8,  position:'MID' },
  { team_code:'KSA', name:'Abdullah Al-Khaibari',  shirt_number:14, position:'DEF' },

  // URU - Uruguay
  { team_code:'URU', name:'Fernando Muslera',      shirt_number:1,  position:'GK'  },
  { team_code:'URU', name:'José María Giménez',    shirt_number:2,  position:'DEF' },
  { team_code:'URU', name:'Ronald Araújo',         shirt_number:4,  position:'DEF' },
  { team_code:'URU', name:'Guillermo Varela',      shirt_number:3,  position:'DEF' },
  { team_code:'URU', name:'Mathías Olivera',       shirt_number:6,  position:'DEF' },
  { team_code:'URU', name:'Lucas Torreira',        shirt_number:5,  position:'MID' },
  { team_code:'URU', name:'Rodrigo Bentancur',     shirt_number:8,  position:'MID' },
  { team_code:'URU', name:'Federico Valverde',     shirt_number:7,  position:'MID' },
  { team_code:'URU', name:'Darwin Núñez',          shirt_number:11, position:'DEL' },
  { team_code:'URU', name:'Facundo Pellistri',     shirt_number:17, position:'DEL' },
  { team_code:'URU', name:'Nicolás De La Cruz',    shirt_number:10, position:'MID' },
  { team_code:'URU', name:'Agustín Canobbio',      shirt_number:14, position:'DEL' },
  { team_code:'URU', name:'Maxi Gómez',            shirt_number:9,  position:'DEL' },

  // ─── GRUPO I ───────────────────────────────────────────────────────────────
  // FRA - Francia
  { team_code:'FRA', name:'Mike Maignan',          shirt_number:1,  position:'GK'  },
  { team_code:'FRA', name:'William Saliba',        shirt_number:5,  position:'DEF' },
  { team_code:'FRA', name:'Jules Koundé',          shirt_number:4,  position:'DEF' },
  { team_code:'FRA', name:'Theo Hernández',        shirt_number:3,  position:'DEF' },
  { team_code:'FRA', name:'Ferland Mendy',         shirt_number:6,  position:'DEF' },
  { team_code:'FRA', name:'Aurélien Tchouaméni',   shirt_number:8,  position:'MID' },
  { team_code:'FRA', name:'Adrien Rabiot',         shirt_number:14, position:'MID' },
  { team_code:'FRA', name:'Warren Zaïre-Emery',    shirt_number:15, position:'MID' },
  { team_code:'FRA', name:'Antoine Griezmann',     shirt_number:7,  position:'DEL' },
  { team_code:'FRA', name:'Kylian Mbappé',         shirt_number:10, position:'DEL' },
  { team_code:'FRA', name:'Ousmane Dembélé',       shirt_number:11, position:'DEL' },
  { team_code:'FRA', name:'Marcus Thuram',         shirt_number:9,  position:'DEL' },
  { team_code:'FRA', name:'Randal Kolo Muani',     shirt_number:21, position:'DEL' },
  { team_code:'FRA', name:'Bradley Barcola',       shirt_number:17, position:'DEL' },
  { team_code:'FRA', name:'N\'Golo Kanté',         shirt_number:13, position:'MID' },

  // SEN - Senegal
  { team_code:'SEN', name:'Édouard Mendy',         shirt_number:1,  position:'GK'  },
  { team_code:'SEN', name:'Kalidou Koulibaly',     shirt_number:3,  position:'DEF' },
  { team_code:'SEN', name:'Abdou Diallo',          shirt_number:5,  position:'DEF' },
  { team_code:'SEN', name:'Ismail Jakobs',         shirt_number:6,  position:'DEF' },
  { team_code:'SEN', name:'Idrissa Gana Gueye',    shirt_number:8,  position:'MID' },
  { team_code:'SEN', name:'Pape Gueye',            shirt_number:4,  position:'MID' },
  { team_code:'SEN', name:'Lamine Camara',         shirt_number:7,  position:'MID' },
  { team_code:'SEN', name:'Sadio Mané',            shirt_number:10, position:'DEL' },
  { team_code:'SEN', name:'Ismaila Sarr',          shirt_number:11, position:'DEL' },
  { team_code:'SEN', name:'Nicolas Jackson',       shirt_number:9,  position:'DEL' },
  { team_code:'SEN', name:'Iliman Ndiaye',         shirt_number:14, position:'DEL' },
  { team_code:'SEN', name:'Krepin Diatta',         shirt_number:17, position:'DEL' },

  // IRQ - Irak
  { team_code:'IRQ', name:'Jalal Hassan',          shirt_number:1,  position:'GK'  },
  { team_code:'IRQ', name:'Ali Adnan',             shirt_number:3,  position:'DEF' },
  { team_code:'IRQ', name:'Hussein Ali',           shirt_number:4,  position:'DEF' },
  { team_code:'IRQ', name:'Mohammed Fadhil',       shirt_number:5,  position:'DEF' },
  { team_code:'IRQ', name:'Ahmed Yasin',           shirt_number:6,  position:'MID' },
  { team_code:'IRQ', name:'Saad Abdul-Amir',       shirt_number:8,  position:'MID' },
  { team_code:'IRQ', name:'Mohanad Ali',           shirt_number:10, position:'MID' },
  { team_code:'IRQ', name:'Aymen Hussein',         shirt_number:9,  position:'DEL' },
  { team_code:'IRQ', name:'Amjad Attwan',          shirt_number:11, position:'DEL' },
  { team_code:'IRQ', name:'Bashar Resan',          shirt_number:7,  position:'DEL' },
  { team_code:'IRQ', name:'Mustafa Nadhim',        shirt_number:14, position:'MID' },

  // NOR - Noruega
  { team_code:'NOR', name:'Ørjan Nyland',          shirt_number:1,  position:'GK'  },
  { team_code:'NOR', name:'Leo Skiri Østigård',    shirt_number:5,  position:'DEF' },
  { team_code:'NOR', name:'Stefan Strandberg',     shirt_number:4,  position:'DEF' },
  { team_code:'NOR', name:'Marcus Pedersen',       shirt_number:2,  position:'DEF' },
  { team_code:'NOR', name:'Fredrik Aursnes',       shirt_number:8,  position:'MID' },
  { team_code:'NOR', name:'Martin Ødegaard',       shirt_number:10, position:'MID' },
  { team_code:'NOR', name:'Mathias Normann',       shirt_number:6,  position:'MID' },
  { team_code:'NOR', name:'Mohamed Elyounoussi',   shirt_number:7,  position:'DEL' },
  { team_code:'NOR', name:'Erling Haaland',        shirt_number:9,  position:'DEL' },
  { team_code:'NOR', name:'Alexander Sørloth',     shirt_number:11, position:'DEL' },
  { team_code:'NOR', name:'Jørgen Strand Larsen',  shirt_number:17, position:'DEL' },
  { team_code:'NOR', name:'Morten Thorsby',        shirt_number:14, position:'MID' },

  // ─── GRUPO J ───────────────────────────────────────────────────────────────
  // ARG - Argentina
  { team_code:'ARG', name:'Emiliano Martínez',     shirt_number:1,  position:'GK'  },
  { team_code:'ARG', name:'Nahuel Molina',         shirt_number:26, position:'DEF' },
  { team_code:'ARG', name:'Gonzalo Montiel',       shirt_number:4,  position:'DEF' },
  { team_code:'ARG', name:'Cristian Romero',       shirt_number:13, position:'DEF' },
  { team_code:'ARG', name:'Lisandro Martínez',     shirt_number:14, position:'DEF' },
  { team_code:'ARG', name:'Nicolás Tagliafico',    shirt_number:3,  position:'DEF' },
  { team_code:'ARG', name:'Rodrigo De Paul',       shirt_number:7,  position:'MID' },
  { team_code:'ARG', name:'Leandro Paredes',       shirt_number:5,  position:'MID' },
  { team_code:'ARG', name:'Alexis Mac Allister',   shirt_number:20, position:'MID' },
  { team_code:'ARG', name:'Enzo Fernández',        shirt_number:24, position:'MID' },
  { team_code:'ARG', name:'Lionel Messi',          shirt_number:10, position:'DEL' },
  { team_code:'ARG', name:'Julián Álvarez',        shirt_number:9,  position:'DEL' },
  { team_code:'ARG', name:'Lautaro Martínez',      shirt_number:22, position:'DEL' },
  { team_code:'ARG', name:'Ángel Di María',        shirt_number:11, position:'DEL' },
  { team_code:'ARG', name:'Alejandro Garnacho',    shirt_number:21, position:'DEL' },
  { team_code:'ARG', name:'Paulo Dybala',          shirt_number:18, position:'DEL' },

  // ALG - Argelia
  { team_code:'ALG', name:'Rais M\'Bolhi',         shirt_number:1,  position:'GK'  },
  { team_code:'ALG', name:'Ramy Bensebaini',       shirt_number:3,  position:'DEF' },
  { team_code:'ALG', name:'Youcef Atal',           shirt_number:2,  position:'DEF' },
  { team_code:'ALG', name:'Aissa Mandi',           shirt_number:5,  position:'DEF' },
  { team_code:'ALG', name:'Sofiane Feghouli',      shirt_number:7,  position:'MID' },
  { team_code:'ALG', name:'Ismael Bennacer',       shirt_number:8,  position:'MID' },
  { team_code:'ALG', name:'Houssem Aouar',         shirt_number:10, position:'MID' },
  { team_code:'ALG', name:'Riyad Mahrez',          shirt_number:11, position:'DEL' },
  { team_code:'ALG', name:'Said Benrahma',         shirt_number:9,  position:'DEL' },
  { team_code:'ALG', name:'Adam Ounas',            shirt_number:14, position:'DEL' },
  { team_code:'ALG', name:'Anis Hadj Moussa',      shirt_number:17, position:'DEL' },
  { team_code:'ALG', name:'Yacine Brahimi',        shirt_number:16, position:'MID' },

  // AUT - Austria
  { team_code:'AUT', name:'Patrick Pentz',         shirt_number:1,  position:'GK'  },
  { team_code:'AUT', name:'David Alaba',           shirt_number:8,  position:'DEF' },
  { team_code:'AUT', name:'Stefan Posch',          shirt_number:5,  position:'DEF' },
  { team_code:'AUT', name:'Philipp Lienhart',      shirt_number:4,  position:'DEF' },
  { team_code:'AUT', name:'Maximilian Wöber',      shirt_number:3,  position:'DEF' },
  { team_code:'AUT', name:'Xaver Schlager',        shirt_number:6,  position:'MID' },
  { team_code:'AUT', name:'Marcel Sabitzer',       shirt_number:7,  position:'MID' },
  { team_code:'AUT', name:'Christoph Baumgartner', shirt_number:10, position:'MID' },
  { team_code:'AUT', name:'Michael Gregoritsch',   shirt_number:9,  position:'DEL' },
  { team_code:'AUT', name:'Sasa Kalajdzic',        shirt_number:11, position:'DEL' },
  { team_code:'AUT', name:'Patrick Wimmer',        shirt_number:14, position:'MID' },
  { team_code:'AUT', name:'Nicolas Seiwald',       shirt_number:16, position:'MID' },
  { team_code:'AUT', name:'Marko Arnautović',      shirt_number:22, position:'DEL' },

  // JOR - Jordania
  { team_code:'JOR', name:'Yazeed Abulaila',       shirt_number:1,  position:'GK'  },
  { team_code:'JOR', name:'Baha Faisal',           shirt_number:5,  position:'DEF' },
  { team_code:'JOR', name:'Rami Hamdan',           shirt_number:4,  position:'DEF' },
  { team_code:'JOR', name:'Abdullah Nasib',        shirt_number:3,  position:'DEF' },
  { team_code:'JOR', name:'Laith Al-Atary',        shirt_number:6,  position:'MID' },
  { team_code:'JOR', name:'Musa Al-Taamari',       shirt_number:10, position:'MID' },
  { team_code:'JOR', name:'Ahmad Habashneh',       shirt_number:8,  position:'MID' },
  { team_code:'JOR', name:'Hamza Al-Dardour',      shirt_number:9,  position:'DEL' },
  { team_code:'JOR', name:'Yousef Malkawi',        shirt_number:11, position:'DEL' },
  { team_code:'JOR', name:'Salam Al-Aqqad',        shirt_number:7,  position:'DEL' },
  { team_code:'JOR', name:'Ali Olwan',             shirt_number:14, position:'MID' },

  // ─── GRUPO K ───────────────────────────────────────────────────────────────
  // POR - Portugal
  { team_code:'POR', name:'Diogo Costa',           shirt_number:1,  position:'GK'  },
  { team_code:'POR', name:'Rúben Dias',            shirt_number:4,  position:'DEF' },
  { team_code:'POR', name:'Nuno Mendes',           shirt_number:3,  position:'DEF' },
  { team_code:'POR', name:'João Cancelo',          shirt_number:20, position:'DEF' },
  { team_code:'POR', name:'Gonçalo Inácio',        shirt_number:5,  position:'DEF' },
  { team_code:'POR', name:'Rúben Neves',           shirt_number:8,  position:'MID' },
  { team_code:'POR', name:'Vitinha',               shirt_number:16, position:'MID' },
  { team_code:'POR', name:'Bruno Fernandes',       shirt_number:8,  position:'MID' },
  { team_code:'POR', name:'Bernardo Silva',        shirt_number:10, position:'MID' },
  { team_code:'POR', name:'Pedro Neto',            shirt_number:7,  position:'DEL' },
  { team_code:'POR', name:'Rafael Leão',           shirt_number:11, position:'DEL' },
  { team_code:'POR', name:'Diogo Jota',            shirt_number:11, position:'DEL' },
  { team_code:'POR', name:'João Félix',            shirt_number:11, position:'DEL' },
  { team_code:'POR', name:'Cristiano Ronaldo',     shirt_number:7,  position:'DEL' },
  { team_code:'POR', name:'Gonçalo Ramos',         shirt_number:9,  position:'DEL' },

  // COD - RD Congo
  { team_code:'COD', name:'Joël Kiassumbua',       shirt_number:1,  position:'GK'  },
  { team_code:'COD', name:'Chancel Mbemba',        shirt_number:5,  position:'DEF' },
  { team_code:'COD', name:'Willy Boly',            shirt_number:4,  position:'DEF' },
  { team_code:'COD', name:'Arthur Masuaku',        shirt_number:3,  position:'DEF' },
  { team_code:'COD', name:'Jordan Ikoko',          shirt_number:2,  position:'DEF' },
  { team_code:'COD', name:'Cédric Bakambu',        shirt_number:9,  position:'DEL' },
  { team_code:'COD', name:'Yoane Wissa',           shirt_number:11, position:'DEL' },
  { team_code:'COD', name:'Neeskens Kebano',       shirt_number:7,  position:'MID' },
  { team_code:'COD', name:'Theo Bongonda',         shirt_number:10, position:'DEL' },
  { team_code:'COD', name:'Silas Mvumpa',          shirt_number:14, position:'DEL' },
  { team_code:'COD', name:'Aly Mabika',            shirt_number:6,  position:'MID' },

  // UZB - Uzbekistán
  { team_code:'UZB', name:'Abduvohid Nematov',     shirt_number:1,  position:'GK'  },
  { team_code:'UZB', name:'Eldor Shomurodov',      shirt_number:9,  position:'DEL' },
  { team_code:'UZB', name:'Jaloliddin Masharipov', shirt_number:10, position:'MID' },
  { team_code:'UZB', name:'Laziz Azimov',          shirt_number:7,  position:'MID' },
  { team_code:'UZB', name:'Khojimat Erkinov',      shirt_number:5,  position:'DEF' },
  { team_code:'UZB', name:'Otabek Shukurov',       shirt_number:6,  position:'MID' },
  { team_code:'UZB', name:'Dostonbek Khamdamov',   shirt_number:11, position:'DEL' },
  { team_code:'UZB', name:'Shokhrukh Lutfullayev', shirt_number:8,  position:'MID' },
  { team_code:'UZB', name:'Ruslan Nishonov',       shirt_number:4,  position:'DEF' },
  { team_code:'UZB', name:'Dilshod Yusupov',       shirt_number:3,  position:'DEF' },
  { team_code:'UZB', name:'Akbar Tursunov',        shirt_number:14, position:'DEL' },

  // COL - Colombia
  { team_code:'COL', name:'Camilo Vargas',         shirt_number:1,  position:'GK'  },
  { team_code:'COL', name:'Davinson Sánchez',      shirt_number:4,  position:'DEF' },
  { team_code:'COL', name:'Daniel Muñoz',          shirt_number:2,  position:'DEF' },
  { team_code:'COL', name:'Johan Mojica',          shirt_number:3,  position:'DEF' },
  { team_code:'COL', name:'Wilmar Barrios',        shirt_number:5,  position:'MID' },
  { team_code:'COL', name:'Mateus Uribe',          shirt_number:8,  position:'MID' },
  { team_code:'COL', name:'James Rodríguez',       shirt_number:10, position:'MID' },
  { team_code:'COL', name:'Luis Díaz',             shirt_number:7,  position:'DEL' },
  { team_code:'COL', name:'Jhon Córdoba',          shirt_number:9,  position:'DEL' },
  { team_code:'COL', name:'Cucho Hernández',       shirt_number:11, position:'DEL' },
  { team_code:'COL', name:'Jhon Arias',            shirt_number:17, position:'DEL' },
  { team_code:'COL', name:'Jorge Carrascal',       shirt_number:14, position:'MID' },
  { team_code:'COL', name:'Rafael Santos Borré',   shirt_number:19, position:'DEL' },

  // ─── GRUPO L ───────────────────────────────────────────────────────────────
  // ENG - Inglaterra
  { team_code:'ENG', name:'Jordan Pickford',       shirt_number:1,  position:'GK'  },
  { team_code:'ENG', name:'Kyle Walker',           shirt_number:2,  position:'DEF' },
  { team_code:'ENG', name:'John Stones',           shirt_number:5,  position:'DEF' },
  { team_code:'ENG', name:'Harry Maguire',         shirt_number:6,  position:'DEF' },
  { team_code:'ENG', name:'Luke Shaw',             shirt_number:3,  position:'DEF' },
  { team_code:'ENG', name:'Declan Rice',           shirt_number:4,  position:'MID' },
  { team_code:'ENG', name:'Jude Bellingham',       shirt_number:22, position:'MID' },
  { team_code:'ENG', name:'Phil Foden',            shirt_number:11, position:'MID' },
  { team_code:'ENG', name:'Bukayo Saka',           shirt_number:7,  position:'DEL' },
  { team_code:'ENG', name:'Harry Kane',            shirt_number:9,  position:'DEL' },
  { team_code:'ENG', name:'Cole Palmer',           shirt_number:20, position:'MID' },
  { team_code:'ENG', name:'Ollie Watkins',         shirt_number:19, position:'DEL' },
  { team_code:'ENG', name:'Marcus Rashford',       shirt_number:10, position:'DEL' },
  { team_code:'ENG', name:'Jack Grealish',         shirt_number:7,  position:'DEL' },
  { team_code:'ENG', name:'Anthony Gordon',        shirt_number:14, position:'DEL' },
  { team_code:'ENG', name:'Kieran Trippier',       shirt_number:12, position:'DEF' },

  // CRO - Croacia
  { team_code:'CRO', name:'Dominik Livaković',     shirt_number:1,  position:'GK'  },
  { team_code:'CRO', name:'Josip Juranović',       shirt_number:2,  position:'DEF' },
  { team_code:'CRO', name:'Joško Gvardiol',        shirt_number:3,  position:'DEF' },
  { team_code:'CRO', name:'Borna Sosa',            shirt_number:6,  position:'DEF' },
  { team_code:'CRO', name:'Luka Modrić',           shirt_number:10, position:'MID' },
  { team_code:'CRO', name:'Mateo Kovačić',         shirt_number:8,  position:'MID' },
  { team_code:'CRO', name:'Marcelo Brozović',      shirt_number:11, position:'MID' },
  { team_code:'CRO', name:'Mario Pašalić',         shirt_number:13, position:'MID' },
  { team_code:'CRO', name:'Ivan Perišić',          shirt_number:4,  position:'DEL' },
  { team_code:'CRO', name:'Andrej Kramarić',       shirt_number:9,  position:'DEL' },
  { team_code:'CRO', name:'Nikola Vlašić',         shirt_number:7,  position:'MID' },
  { team_code:'CRO', name:'Ante Budimir',          shirt_number:17, position:'DEL' },
  { team_code:'CRO', name:'Bruno Petković',        shirt_number:19, position:'DEL' },
  { team_code:'CRO', name:'Mislav Oršić',          shirt_number:15, position:'DEL' },

  // GHA - Ghana
  { team_code:'GHA', name:'Lawrence Ati-Zigi',     shirt_number:1,  position:'GK'  },
  { team_code:'GHA', name:'Daniel Amartey',        shirt_number:5,  position:'DEF' },
  { team_code:'GHA', name:'Alexander Djiku',       shirt_number:4,  position:'DEF' },
  { team_code:'GHA', name:'Tariq Lamptey',         shirt_number:2,  position:'DEF' },
  { team_code:'GHA', name:'Baba Rahman',           shirt_number:3,  position:'DEF' },
  { team_code:'GHA', name:'Thomas Partey',         shirt_number:6,  position:'MID' },
  { team_code:'GHA', name:'Mohammed Kudus',        shirt_number:10, position:'MID' },
  { team_code:'GHA', name:'Jordan Ayew',           shirt_number:9,  position:'DEL' },
  { team_code:'GHA', name:'Antoine Semenyo',       shirt_number:11, position:'DEL' },
  { team_code:'GHA', name:'Iñaki Williams',        shirt_number:7,  position:'DEL' },
  { team_code:'GHA', name:'Kamaldeen Sulemana',    shirt_number:14, position:'DEL' },
  { team_code:'GHA', name:'Ernest Nuamah',         shirt_number:17, position:'DEL' },
  { team_code:'GHA', name:'Abdul Fatawu',          shirt_number:19, position:'DEL' },

  // PAN - Panamá
  { team_code:'PAN', name:'Luis Mejía',            shirt_number:1,  position:'GK'  },
  { team_code:'PAN', name:'Harold Cummings',       shirt_number:4,  position:'DEF' },
  { team_code:'PAN', name:'Fidel Escobar',         shirt_number:5,  position:'DEF' },
  { team_code:'PAN', name:'Adolfo Machado',        shirt_number:3,  position:'DEF' },
  { team_code:'PAN', name:'Roderick Miller',       shirt_number:2,  position:'DEF' },
  { team_code:'PAN', name:'Anibal Godoy',          shirt_number:6,  position:'MID' },
  { team_code:'PAN', name:'Adalberto Carrasquilla',shirt_number:8,  position:'MID' },
  { team_code:'PAN', name:'José Luis Rodríguez',   shirt_number:7,  position:'DEL' },
  { team_code:'PAN', name:'Rolando Blackburn',     shirt_number:9,  position:'DEL' },
  { team_code:'PAN', name:'Édgar Bárcenas',        shirt_number:11, position:'DEL' },
  { team_code:'PAN', name:'Cecilio Waterman',      shirt_number:10, position:'DEL' },
  { team_code:'PAN', name:'Gabriel Torres',        shirt_number:17, position:'DEL' },
]
